# oops

In [2]:
class bike():
    gear = 0
    bike_name = '' #empty

In [3]:
bike1 = bike() #class instanse

In [4]:
bike1.bike_name = 'Honda'

In [5]:
bike1.bike_name

'Honda'

In [6]:
bike1.gear = 5
bike1.gear

5

In [7]:
bike2 = bike()

In [8]:
bike2.gear , bike1.gear

(0, 5)

In [9]:
class calculate_area():
    length = 0
    breadth = 0
    def area (self, length, breadth):
        self.length = length
        self.breadth = breadth
        return length * breadth, 'msq'

In [10]:
room = calculate_area()

In [11]:
room.area(20, 35)

(700, 'msq')

# Modules

In [13]:
# NUMPY (Numerical Python)

In [14]:
# it is used in ml. It provides a array data
# for faster processing speed

In [15]:
import numpy as np

In [16]:
np.__version__

'1.26.4'

In [17]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim

1

In [20]:
two_d_arr = np.array([[4,5], [7,8]])
two_d_arr

array([[4, 5],
       [7, 8]])

In [21]:
two_d_arr.ndim

2

In [22]:
arr.shape

(8,)

In [23]:
arr.shape, arr.size

((8,), 8)

In [24]:
two_d_arr.shape

(2, 2)

In [25]:
two_d_arr.size

4

In [26]:
three_d_arr = np.array([[[4,5], [7,8], [0,5], [3,2], [1,7], [4,5], [10,3], [8,4], [7,0]]])
three_d_arr

array([[[ 4,  5],
        [ 7,  8],
        [ 0,  5],
        [ 3,  2],
        [ 1,  7],
        [ 4,  5],
        [10,  3],
        [ 8,  4],
        [ 7,  0]]])

In [27]:
three_d_arr.ndim

3

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [31]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [32]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [34]:
np.random.rand(10) # it will give u a array from 0 to 1

array([0.02571921, 0.34320242, 0.87719925, 0.31037595, 0.4169902 ,
       0.72651668, 0.65427632, 0.92486448, 0.49258245, 0.89343516])

In [35]:
np.random.rand(10)*100

array([40.98309496,  1.82308499, 76.662483  , 76.98041347,  0.57177639,
       88.27163814, 84.14202407, 84.05032657, 29.76082764,  7.02910474])

In [36]:
np.random.rand(4,5)

array([[0.87531508, 0.48661226, 0.17076635, 0.66918331, 0.46748501],
       [0.68208425, 0.94442747, 0.17970509, 0.85149571, 0.41533368],
       [0.27335693, 0.21700646, 0.08164229, 0.13549067, 0.4578774 ],
       [0.3366243 , 0.67435166, 0.34426812, 0.42075732, 0.97496878]])

In [37]:
(np.random.rand(4,5)*100).astype('int64')

array([[14, 92, 32, 15, 53],
       [90, 15, 76, 29, 29],
       [67,  8, 20, 32, 59],
       [40, 95, 47, 10, 58]], dtype=int64)

In [38]:
np.random.randint(0,5)

2

In [39]:
np.random.randint(1,10,(4,4))

array([[7, 9, 9, 8],
       [1, 9, 9, 8],
       [7, 1, 6, 3],
       [3, 2, 1, 1]])

In [40]:
# mathematical expression using NUMPY

In [80]:
a = np.random.randint(1,20,(2,2))
b = np.random.randint(1,20,(2,2))
a,b

(array([[ 7, 18],
        [ 2,  2]]),
 array([[ 5, 17],
        [ 7,  9]]))

In [82]:
np.add(a,b)

array([[12, 35],
       [ 9, 11]])

In [84]:
np.multiply(a,b)

array([[ 35, 306],
       [ 14,  18]])

In [86]:
np.subtract(a,b)

array([[ 2,  1],
       [-5, -7]])

In [88]:
np.divide(a,b)

array([[1.4       , 1.05882353],
       [0.28571429, 0.22222222]])

In [90]:
np.divide(b,a)

array([[0.71428571, 0.94444444],
       [3.5       , 4.5       ]])

In [92]:
np.mod(a,b)

array([[2, 1],
       [2, 2]])

In [94]:
np.sqrt(a)

array([[2.64575131, 4.24264069],
       [1.41421356, 1.41421356]])

In [96]:
np.sqrt(b)

array([[2.23606798, 4.12310563],
       [2.64575131, 3.        ]])

In [98]:
np.power(a,2)

array([[ 49, 324],
       [  4,   4]], dtype=int32)

In [100]:
np.tan(a)

array([[ 0.87144798, -1.13731371],
       [-2.18503986, -2.18503986]])

In [102]:
cosec = 1/np.sin(a)
cosec

array([[ 1.52210106, -1.33158054],
       [ 1.09975017,  1.09975017]])

In [104]:
#statistical function

In [106]:
a

array([[ 7, 18],
       [ 2,  2]])

In [108]:
a.max()

18

In [110]:
a.argmax()

1

In [112]:
a.min()

2

In [114]:
a.argmin()

2

In [118]:
a.mean()

7.25

In [122]:
np.median(a)

4.5

In [124]:
a

array([[ 7, 18],
       [ 2,  2]])

In [126]:
np.median(b)

8.0

In [128]:
b

array([[ 5, 17],
       [ 7,  9]])

In [130]:
a.std()

6.53356717268599

In [132]:
a.var()

42.6875

In [134]:
np.cumsum(a)

array([ 7, 25, 27, 29])

In [136]:
a

array([[ 7, 18],
       [ 2,  2]])

In [140]:
a.repeat(3)

array([ 7,  7,  7, 18, 18, 18,  2,  2,  2,  2,  2,  2])

In [142]:
np.dot(a,b)

array([[161, 281],
       [ 24,  52]])

In [144]:
np.cross(a,b)

array([29,  4])

In [146]:
np.transpose(a)

array([[ 7,  2],
       [18,  2]])

In [150]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
a1[1,2]

6

In [156]:
# indexing

In [158]:
a1[1,2]

6

In [160]:
a1[1,1]

5

In [162]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
a1[0:2:1,::]

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
a1[::,0:2:1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [176]:
a1[1:3:1,1:3:1]

array([[5, 6],
       [8, 9]])

In [178]:
# concatenation

In [180]:
np.concatenate((a,b),axis=1) # horizontal addition

array([[ 7, 18,  5, 17],
       [ 2,  2,  7,  9]])

In [182]:
np.concatenate((a,b),axis=0) # row addition /vertical addition

array([[ 7, 18],
       [ 2,  2],
       [ 5, 17],
       [ 7,  9]])

In [186]:
np.vstack((a,b))

array([[ 7, 18],
       [ 2,  2],
       [ 5, 17],
       [ 7,  9]])

In [188]:
np.hstack((a,b))

array([[ 7, 18,  5, 17],
       [ 2,  2,  7,  9]])